### ISSUE TITLE
Error while adding clooney using cdn

### ISSUE THREAD

**Issue by denar90** [GoogleChromeLabs/clooney#14]
Hi 👋 I've been trying to play with it and faced strange issue.
Adding it on a page 
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/clooneyjs@0.4.2/clooney.bundle.js"></script>


    <title>Title</title>
</head>
<body>
<script>
  async function main() {
    class X{
      log() {
        console.log('hai');
        return 4;
      }
    }
    const x = await Clooney.spawn(X);
    console.log(await x.log());
  }
  main();
</script>
</body>
</html>
```

I get error in console

```
Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'https://cdn.jsdelivr.net/npm/clooneyjs@0.4.2/clooney.bundle.js' cannot be accessed from origin 'http://localhost:8000'.
    at Object.newWorkerFunc (https://cdn.jsdelivr.net/npm/clooneyjs@0.4.2/clooney.bundle.js:352:32)
    at RoundRobinStrategy._initOrGetContainer (https://cdn.jsdelivr.net/npm/clooneyjs@0.4.2/clooney.bundle.js:367:48)
    at RoundRobinStrategy._getNextContainer (https://cdn.jsdelivr.net/npm/clooneyjs@0.4.2/clooney.bundle.js:377:30)
    at RoundRobinStrategy.spawn (https://cdn.jsdelivr.net/npm/clooneyjs@0.4.2/clooney.bundle.js:382:38)
    at Object.spawn (https://cdn.jsdelivr.net/npm/clooneyjs@0.4.2/clooney.bundle.js:395:28)
    at main (http://localhost:8000/:19:29)
    at http://localhost:8000/:22:3
```

If file copied and loaded locally everything is fine.

**Comment by surma** [comment]
Please don’t just copy the CDN URL, but also read the text that comes along with it: https://github.com/GoogleChromeLabs/clooney#cdn
